# Análise de Dados

## Gerando estatísticas

### Carregando os dados

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('datasets/base_dados_vendas_tratada.csv', parse_dates=['dt_venda', 'dt_entrega'], index_col='dt_venda')

In [4]:
df = df.astype({
    'matricula_funcionario': 'str',
    'codigo_produto': 'str'
})

In [5]:
df.head()

,matricula_funcionario,nome_funcionario,cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,categoria,preco_custo,valor_unitario,quantidade,dt_entrega,valor_final,lucro
dt_venda,,,,,,,,,,,,,,
2020-08-25 10:04:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10013,Fogão,Eletrodomésticos,210.9,404.1,3,2020-08-31 16:39:00,1212.3,1001.4
2020-06-10 15:34:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10011,Liquidificador,Cozinha,59.9,142.4,2,2020-06-11 13:59:00,284.8,224.9
2019-03-21 15:58:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10013,Fogão,Eletrodomésticos,210.9,404.1,2,2019-03-28 09:44:00,808.2,597.3
2019-09-16 14:46:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10004,Máquina Lavar Roupa,Eletrodomésticos,1099.0,1709.1,2,2019-09-20 09:22:00,3418.2,2319.2
2019-11-25 16:28:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10005,Notebook,Eletrônicos,2299.9,3199.0,2,2019-11-26 13:42:00,6398.0,4098.1

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 3000 entries, 2020-08-25 10:04:00 to 2019-03-18 15:40:00
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   matricula_funcionario  3000 non-null   object
 1   nome_funcionario       3000 non-null   object
 2   cargo                  3000 non-null   object
 3   codigo_loja            3000 non-null   object
 4   nome_loja              3000 non-null   object
 5   codigo_produto         3000 non-null   object
 6   descricao_produto      3000 non-null   object
 7   categoria              3000 non-null   object
 8   preco_custo            3000 non-null   float64
 9   valor_unitario         3000 non-null   float64
 10  quantidade             3000 non-null   int64
 11  dt_entrega             3000 non-null   datetime64[ns]
 12  valor_final            3000 non-null   float64
 13  lucro                  3000 non-null   float64
dtypes: datetime64[ns](1), float64(4), int64(1), object(8)
memory usage: 351.6+ KB

### describe

Gera estatísticas de um DataFrame ou Series.
```python
describe()
```

In [7]:
df.describe()[['preco_custo', 'valor_unitario', 'valor_final','lucro']].round(2)

       preco_custo  valor_unitario  valor_final     lucro
count      3000.00         3000.00      3000.00   3000.00
mean        545.51          926.94      2234.95   1689.44
std         563.13          841.84      2449.47   2018.82
min          27.90           55.90        55.90     28.00
25%         109.90          189.90       427.20    344.20
50%         210.90          404.10      1346.90    709.60
75%         799.00         1424.91      3353.80   2453.90
max        2299.90         3199.00     12796.00  10496.10

### count

Conta a quantidade de valores não nulos de uma coluna.
```python
count()
```

In [8]:
df.count()

matricula_funcionario    3000
nome_funcionario         3000
cargo                    3000
codigo_loja              3000
nome_loja                3000
codigo_produto           3000
descricao_produto        3000
categoria                3000
preco_custo              3000
valor_unitario           3000
quantidade               3000
dt_entrega               3000
valor_final              3000
lucro                    3000
dtype: int64

In [9]:
df['codigo_produto'].count()

3000

### sum

Soma os valores de linhas ou colunas.
```python
sum()
```

In [10]:
colunas = ['preco_custo', 'valor_unitario', 'valor_final','lucro']
df[colunas].sum()

preco_custo       1636536.90
valor_unitario    2780824.06
valor_final       6704846.61
lucro             5068309.71
dtype: float64

In [11]:
df['valor_final'].sum().round(2)

6704846.61

In [12]:
df.head()

,matricula_funcionario,nome_funcionario,cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,categoria,preco_custo,valor_unitario,quantidade,dt_entrega,valor_final,lucro
dt_venda,,,,,,,,,,,,,,
2020-08-25 10:04:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10013,Fogão,Eletrodomésticos,210.9,404.1,3,2020-08-31 16:39:00,1212.3,1001.4
2020-06-10 15:34:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10011,Liquidificador,Cozinha,59.9,142.4,2,2020-06-11 13:59:00,284.8,224.9
2019-03-21 15:58:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10013,Fogão,Eletrodomésticos,210.9,404.1,2,2019-03-28 09:44:00,808.2,597.3
2019-09-16 14:46:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10004,Máquina Lavar Roupa,Eletrodomésticos,1099.0,1709.1,2,2019-09-20 09:22:00,3418.2,2319.2
2019-11-25 16:28:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10005,Notebook,Eletrônicos,2299.9,3199.0,2,2019-11-26 13:42:00,6398.0,4098.1

In [13]:
import numpy as np

In [14]:
np.sum(df[colunas], axis='columns')

dt_venda
2020-08-25 10:04:00     2828.7
2020-06-10 15:34:00      712.0
2019-03-21 15:58:00     2020.5
2019-09-16 14:46:00     8545.5
2019-11-25 16:28:00    15995.0
                        ...
2019-04-17 15:36:00    17095.5
2020-01-21 15:46:00     1249.5
2020-10-22 17:06:00      949.5
2019-02-18 16:04:00     1212.3
2019-03-18 15:40:00    11963.7
Length: 3000, dtype: float64

### média aritmética

Calcula a média aritmética.
```python
mean()
```

In [15]:
df.head()

,matricula_funcionario,nome_funcionario,cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,categoria,preco_custo,valor_unitario,quantidade,dt_entrega,valor_final,lucro
dt_venda,,,,,,,,,,,,,,
2020-08-25 10:04:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10013,Fogão,Eletrodomésticos,210.9,404.1,3,2020-08-31 16:39:00,1212.3,1001.4
2020-06-10 15:34:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10011,Liquidificador,Cozinha,59.9,142.4,2,2020-06-11 13:59:00,284.8,224.9
2019-03-21 15:58:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10013,Fogão,Eletrodomésticos,210.9,404.1,2,2019-03-28 09:44:00,808.2,597.3
2019-09-16 14:46:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10004,Máquina Lavar Roupa,Eletrodomésticos,1099.0,1709.1,2,2019-09-20 09:22:00,3418.2,2319.2
2019-11-25 16:28:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10005,Notebook,Eletrônicos,2299.9,3199.0,2,2019-11-26 13:42:00,6398.0,4098.1

In [16]:
df[colunas].mean()
# OU :
# np.mean(df[colunas], axis='rows') PARA LINHAS
# np.mean(df[colunas], axis='columns') PARA COLUNAS

preco_custo        545.512300
valor_unitario     926.941353
valor_final       2234.948870
lucro             1689.436570
dtype: float64

### mediana

Calcula a mediana.
```python
median()
```

In [19]:
df[colunas].median()

preco_custo        210.9
valor_unitario     404.1
valor_final       1346.9
lucro              709.6
dtype: float64

### moda

Calcula a moda.
```python
mode()
```

In [22]:
df['descricao_produto'].mode()

0    Aspirador de pó
Name: descricao_produto, dtype: object

### desvio padrão

Calcula o desvio padrão.
```python
std()
```

In [23]:
df[colunas].std().round(2)

preco_custo        563.13
valor_unitario     841.84
valor_final       2449.47
lucro             2018.82
dtype: float64

### quantis

Calcula os percentis.
```python
quantile()
```

In [24]:
df[colunas].quantile(0.75)

preco_custo        799.00
valor_unitario    1424.91
valor_final       3353.80
lucro             2453.90
Name: 0.75, dtype: float64

### contando valores

Realiza a contagem dos valores de uma coluna.
```python
value_counts()
```

In [37]:
df['descricao_produto'].value_counts().sort_index()
# SORT_INDEX ORDENA EM ORDEM ALFABETICA

Aspirador de pó             173
Batedeira                   136
Cafeteira                   136
Cama Box                    146
Colchão                     150
Ferro de passar             151
Fogão                       163
Fritadeira elétrica         153
Geladeira                   142
Guarda Roupa                149
Impressora                  154
Liquidificador              156
Microondas                  162
Máquina Lavar Roupa         159
Notebook                    131
Processador de alimentos    143
Smartphone                  154
Sofá                        138
Tablet                      155
Televisão                   149
Name: descricao_produto, dtype: int64

## Filtrando os dados

### Testes lógicos

In [38]:
df.head()

,matricula_funcionario,nome_funcionario,cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,categoria,preco_custo,valor_unitario,quantidade,dt_entrega,valor_final,lucro
dt_venda,,,,,,,,,,,,,,
2020-08-25 10:04:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10013,Fogão,Eletrodomésticos,210.9,404.1,3,2020-08-31 16:39:00,1212.3,1001.4
2020-06-10 15:34:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10011,Liquidificador,Cozinha,59.9,142.4,2,2020-06-11 13:59:00,284.8,224.9
2019-03-21 15:58:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10013,Fogão,Eletrodomésticos,210.9,404.1,2,2019-03-28 09:44:00,808.2,597.3
2019-09-16 14:46:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10004,Máquina Lavar Roupa,Eletrodomésticos,1099.0,1709.1,2,2019-09-20 09:22:00,3418.2,2319.2
2019-11-25 16:28:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10005,Notebook,Eletrônicos,2299.9,3199.0,2,2019-11-26 13:42:00,6398.0,4098.1

In [39]:
filtro_valor_final = df['valor_final'] < 100

In [40]:
type(df[filtro_valor_final])

pandas.core.frame.DataFrame

In [41]:
df[filtro_valor_final]

,matricula_funcionario,nome_funcionario,cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,categoria,preco_custo,valor_unitario,quantidade,dt_entrega,valor_final,lucro
dt_venda,,,,,,,,,,,,,,
2019-08-31 17:42:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10007,Batedeira,Cozinha,49.9,95.9,1,2019-09-01 12:18:00,95.9,46.0
2020-05-16 14:55:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10007,Batedeira,Cozinha,49.9,95.9,1,2020-05-17 10:34:00,95.9,46.0
2020-10-27 10:31:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10007,Batedeira,Cozinha,49.9,95.9,1,2020-10-27 12:57:00,95.9,46.0
2019-12-30 15:57:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10007,Batedeira,Cozinha,49.9,95.9,1,2019-12-31 11:20:00,95.9,46.0
2020-06-14 17:57:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10009,Ferro de passar,Casa,27.9,55.9,1,2020-06-15 17:17:00,55.9,28.0
2020-01-28 16:50:00,123456333,Jorge Mateus,Vendedor,CL001,Loja Matriz,10009,Ferro de passar,Casa,27.9,55.9,1,2020-01-28 17:42:00,55.9,28.0
2020-10-15 09:34:00,123456333,Jorge Mateus,Vendedor,CL001,Loja Matriz,10009,Ferro de passar,Casa,27.9,55.9,1,2020-10-15 14:37:00,55.9,28.0
2020-05-10 12:21:00,123456111,José Maria,Vendedor,CL001,Loja Matriz,10009,Ferro de passar,Casa,27.9,55.9,1,2020-05-10 13:02:00,55.9,28.0
2019-04-18 11:54:00,123456111,José Maria,Vendedor,CL001,Loja Matriz,10007,Batedeira,Cozinha,49.9,95.9,1,2019-04-18 13:00:00,95.9,46.0
2019-01-01 09:08:00,123456777,Marcos Coelho,Vendedor,CL003,Filial SP,10009,Ferro de passar,Casa,27.9,55.9,1,2019-01-01 14:07:00,55.9,28.0
2020-12-14 10:29:00,123456777,Marcos Coelho,Vendedor,CL003,Filial SP,10009,Ferro de passar,Casa,27.9,55.9,1,2020-12-15 09:40:00,55.9,28.0
2020-05-07 12:07:00,123456777,Marcos Coelho,Vendedor,CL003,Filial SP,10007,Batedeira,Cozinha,49.9,95.9,1,2020-05-07 12:13:00,95.9,46.0
2019-05-31 10:47:00,123456777,Marcos Coelho,Vendedor,CL003,Filial SP,10007,Batedeira,Cozinha,49.9,95.9,1,2019-05-31 12:11:00,95.9,46.0
2019-10-16 14:07:00,123456777,Marcos Coelho,Vendedor,CL003,Filial SP,10007,Batedeira,Cozinha,49.9,95.9,1,2019-10-16 16:39:00,95.9,46.0
2019-04-11 11:56:00,123456777,Marcos Coelho,Vendedor,CL003,Filial SP,10007,Batedeira,Cozinha,49.9,95.9,1,2019-04-11 14:50:00,95.9,46.0
2020-04-05 09:55:00,123456222,Maria das Graças,Vendedor,CL001,Loja Matriz,10009,Ferro de passar,Casa,27.9,55.9,1,2020-04-05 12:07:00,55.9,28.0
2019-09-09 10:31:00,123456222,Maria das Graças,Vendedor,CL001,Loja Matriz,10009,Ferro de passar,Casa,27.9,55.9,1,2019-09-09 14:19:00,55.9,28.0
2020-08-02 10:08:00,123456222,Maria das Graças,Vendedor,CL001,Loja Matriz,10007,Batedeira,Cozinha,49.9,95.9,1,2020-08-02 12:53:00,95.9,46.0
2019-05-04 11:22:00,123456222,Maria das Graças,Vendedor,CL001,Loja Matriz,10007,Batedeira,Cozinha,49.9,95.9,1,2019-05-04 11:30:00,95.9,46.0
2020-05-06 16:26:00,123456555,Marta Cury,Vendedor,CL002,Filial MG,10007,Batedeira,Cozinha,49.9,95.9,1,2020-05-06 17:32:00,95.9,46.0
2020-07-04 16:28:00,123456555,Marta Cury,Vendedor,CL002,Filial MG,10007,Batedeira,Cozinha,49.9,95.9,1,2020-07-05 15:32:00,95.9,46.0
2019-11-12 17:16:00,123456555,Marta Cury,Vendedor,CL002,Filial MG,10009,Ferro de passar,Casa,27.9,55.9,1,2019-11-13 17:04:00,55.9,28.0
2020-09-25 17:07:00,123456555,Marta Cury,Vendedor,CL002,Filial MG,10007,Batedeira,Cozinha,49.9,95.9,1,2020-09-25 17:29:00,95.9,46.0
2020-11-02 10:04:00,123456555,Marta Cury,Vendedor,CL002,Filial MG,10009,Ferro de passar,Casa,27.9,55.9,1,2020-11-02 11:34:00,55.9,28.0
2019-08-30 17:20:00,123456555,Marta Cury,Vendedor,CL002,Filial MG,10007,Batedeira,Cozinha,49.9,95.9,1,2019-08-31 15:37:00,95.9,46.0
2019-02-20 09:13:00,123457112,Mário Henrique,Vendedor,CL004,Filial ES,10009,Ferro de passar,Casa,27.9,55.9,1,2019-02-20 17:39:00,55.9,28.0
2019-11-19 16:50:00,123457112,Mário Henrique,Vendedor,CL004,Filial ES,10009,Ferro de passar,Casa,27.9,55.9,1,2019-11-20 14:32:00,55.9,28.0
2019-11-25 16:19:00,123457112,Mário Henrique,Vendedor,CL004,Filial ES,10009,Ferro de passar,Casa,27.9,55.9,1,2019-11-26 13:20:00,55.9,28.0
2020-02-22 10:31:00,123457111,Pamela Lima,Vendedor,CL004,Filial ES,10007,Batedeira,Cozinha,49.9,95.9,1,2020-02-22 13:28:00,95.9,46.0
2020-11-05 11:31:00,123457111,Pamela Lima,Vendedor,CL004,Filial ES,10007,Batedeira,Cozinha,49.9,95.9,1,2020-11-05 15:25:00,95.9,46.0
2019-06-02 10:40:00,123457111,Pamela Lima,Vendedor,CL004,Filial ES,10009,Ferro de passar,Casa,27.9,55.9,1,2019-06-02 17:53:00,55.9,28.0
2019-10-20 13:57:00,123457111,Pamela Lima,Vendedor,CL004,Filial ES,10007,Batedeira,Cozinha,49.9,95.9,1,2019-10-21 12:35:00,95.9,46.0
2020-09-17 10:32:00,123457111,Pamela Lima,Vendedor,CL004,Filial ES,10009,Ferro de passar,Casa,27.9,55.9,1,2020-09-17 11:56:00,55.9,28.0
2019-10-26 11:39:00,123457111,Pamela Lima,Vendedor,CL004,Filial ES,10007,Batedeira,Cozinha,49.9,95.9,1,2019-10-26 16:42:00,95.9,46.0
2019-03-27 12:36:00,123456666,Reginaldo Sodré,Vendedor,CL002,Filial MG,10007,Batedeira,Cozinha,49.9,95.9,1,2019-03-27 13:52:00,95.9,46.0
2020-07-27 14:32:00,123456666,Reginaldo Sodré,Vendedor,CL002,Filial MG,10009,Ferro de passar,Casa,27.9,55.9,1,2020-07-27 14:35:00,55.9,28.0
2020-08-03 17:00:00,123456666,Reginaldo Sodré,Vendedor,CL002,Filial MG,10009,Ferro de passar,Casa,27.9,55.9,1,2020-08-04 11:52:00,55.9,28.0
2019-01-22 14:37:00,123456666,Reginaldo Sodré,Vendedor,CL002,Filial MG,10009,Ferro de passar,Casa,27.9,55.9,1,2019-01-23 09:06:00,55.9,28.0
2020-11-24 10:01:00,123456666,Reginaldo Sodré,Vendedor,CL002,Filial MG,10009,Ferro de passar,Casa,27.9,55.9,1,2020-11-24 11:33:00,55.9,28.0
2019-01-02 17:30:00,123456666,Reginaldo Sodré,Vendedor,CL002,Filial MG,10007,Batedeira,Cozinha,49.9,95.9,1,2019-01-03 12:52:00,95.9,46.0
2019-06-22 12:56:00,123456444,Ricardo Lemos,Vendedor,CL002,Filial MG,10009,Ferro de passar,Casa,27.9,55.9,1,2019-06-23 12:11:00,55.9,28.0
2019-03-31 09:56:00,123456444,Ricardo Lemos,Vendedor,CL002,Filial MG,10009,Ferro de passar,Casa,27.9,55.9,1,2019-03-31 17:13:00,55.9,28.0
2020-04-25 13:08:00,123456444,Ricardo Lemos,Vendedor,CL002,Filial MG,10009,Ferro de passar,Casa,27.9,55.9,1,2020-04-26 09:50:00,55.9,28.0
2020-04-03 11:23:00,123456444,Ricardo Lemos,Vendedor,CL002,Filial MG,10009,Ferro de passar,Casa,27.9,55.9,1,2020-04-04 09:30:00,55.9,28.0
2019-08-02 15:50:00,123456444,Ricardo Lemos,Vendedor,CL002,Filial MG,10009,Ferro de passar,Casa,27.9,55.9,1,2019-08-03 14:47:00,55.9,28.0
2020-11-03 11:34:00,123456444,Ricardo Lemos,Vendedor,CL002,Filial MG,10007,Batedeira,Cozinha,49.9,95.9,1,2020-11-03 17:59:00,95.9,46.0
2020-09-22 17:00:00,123456444,Ricardo Lemos,Vendedor,CL002,Filial MG,10007,Batedeira,Cozinha,49.9,95.9,1,2020-09-23 11:01:00,95.9,46.0
2019-10-15 09:11:00,123456888,Rita Sampaio,Vendedor,CL003,Filial SP,10007,Batedeira,Cozinha,49.9,95.9,1,2019-10-15 12:33:00,95.9,46.0
2019-09-02 17:20:00,123456888,Rita Sampaio,Vendedor,CL003,Filial SP,10007,Batedeira,Cozinha,49.9,95.9,1,2019-09-02 17:48:00,95.9,46.0
2020-08-05 15:37:00,123456888,Rita Sampaio,Vendedor,CL003,Filial SP,10007,Batedeira,Cozinha,49.9,95.9,1,2020-08-05 16:59:00,95.9,46.0
2019-06-15 11:29:00,123456888,Rita Sampaio,Vendedor,CL003,Filial SP,10009,Ferro de passar,Casa,27.9,55.9,1,2019-06-15 16:52:00,55.9,28.0
2020-03-26 16:56:00,123456888,Rita Sampaio,Vendedor,CL003,Filial SP,10009,Ferro de passar,Casa,27.9,55.9,1,2020-03-27 13:31:00,55.9,28.0
2019-10-22 09:46:00,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10007,Batedeira,Cozinha,49.9,95.9,1,2019-10-22 14:45:00,95.9,46.0
2019-11-27 14:57:00,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10007,Batedeira,Cozinha,49.9,95.9,1,2019-11-28 09:12:00,95.9,46.0
2019-01-10 11:43:00,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10009,Ferro de passar,Casa,27.9,55.9,1,2019-01-10 15:18:00,55.9,28.0
2019-08-09 14:58:00,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10007,Batedeira,Cozinha,49.9,95.9,1,2019-08-09 17:51:00,95.9,46.0
2019-04-14 15:52:00,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10007,Batedeira,Cozinha,49.9,95.9,1,2019-04-15 13:54:00,95.9,46.0
2020-05-06 16:18:00,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10009,Ferro de passar,Casa,27.9,55.9,1,2020-05-07 13:47:00,55.9,28.0
2019-01-05 16:49:00,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10007,Batedeira,Cozinha,49.9,95.9,1,2019-01-06 10:53:00,95.9,46.0

### Operadores lógicos

- and: &
- or : |

In [50]:
filtro_valor_final = df['valor_final'] < 100
filtro_nome_loja = df['nome_loja'] == 'Filial SP'

In [51]:
df_valor_loja =  df[filtro_valor_final & filtro_nome_loja]

In [52]:
df_valor_loja

,matricula_funcionario,nome_funcionario,cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,categoria,preco_custo,valor_unitario,quantidade,dt_entrega,valor_final,lucro
dt_venda,,,,,,,,,,,,,,
2019-08-31 17:42:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10007,Batedeira,Cozinha,49.9,95.9,1,2019-09-01 12:18:00,95.9,46.0
2020-05-16 14:55:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10007,Batedeira,Cozinha,49.9,95.9,1,2020-05-17 10:34:00,95.9,46.0
2020-10-27 10:31:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10007,Batedeira,Cozinha,49.9,95.9,1,2020-10-27 12:57:00,95.9,46.0
2019-12-30 15:57:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10007,Batedeira,Cozinha,49.9,95.9,1,2019-12-31 11:20:00,95.9,46.0
2020-06-14 17:57:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10009,Ferro de passar,Casa,27.9,55.9,1,2020-06-15 17:17:00,55.9,28.0
2019-01-01 09:08:00,123456777,Marcos Coelho,Vendedor,CL003,Filial SP,10009,Ferro de passar,Casa,27.9,55.9,1,2019-01-01 14:07:00,55.9,28.0
2020-12-14 10:29:00,123456777,Marcos Coelho,Vendedor,CL003,Filial SP,10009,Ferro de passar,Casa,27.9,55.9,1,2020-12-15 09:40:00,55.9,28.0
2020-05-07 12:07:00,123456777,Marcos Coelho,Vendedor,CL003,Filial SP,10007,Batedeira,Cozinha,49.9,95.9,1,2020-05-07 12:13:00,95.9,46.0
2019-05-31 10:47:00,123456777,Marcos Coelho,Vendedor,CL003,Filial SP,10007,Batedeira,Cozinha,49.9,95.9,1,2019-05-31 12:11:00,95.9,46.0
2019-10-16 14:07:00,123456777,Marcos Coelho,Vendedor,CL003,Filial SP,10007,Batedeira,Cozinha,49.9,95.9,1,2019-10-16 16:39:00,95.9,46.0
2019-04-11 11:56:00,123456777,Marcos Coelho,Vendedor,CL003,Filial SP,10007,Batedeira,Cozinha,49.9,95.9,1,2019-04-11 14:50:00,95.9,46.0
2019-10-15 09:11:00,123456888,Rita Sampaio,Vendedor,CL003,Filial SP,10007,Batedeira,Cozinha,49.9,95.9,1,2019-10-15 12:33:00,95.9,46.0
2019-09-02 17:20:00,123456888,Rita Sampaio,Vendedor,CL003,Filial SP,10007,Batedeira,Cozinha,49.9,95.9,1,2019-09-02 17:48:00,95.9,46.0
2020-08-05 15:37:00,123456888,Rita Sampaio,Vendedor,CL003,Filial SP,10007,Batedeira,Cozinha,49.9,95.9,1,2020-08-05 16:59:00,95.9,46.0
2019-06-15 11:29:00,123456888,Rita Sampaio,Vendedor,CL003,Filial SP,10009,Ferro de passar,Casa,27.9,55.9,1,2019-06-15 16:52:00,55.9,28.0
2020-03-26 16:56:00,123456888,Rita Sampaio,Vendedor,CL003,Filial SP,10009,Ferro de passar,Casa,27.9,55.9,1,2020-03-27 13:31:00,55.9,28.0

In [54]:
df_valor_loja.describe().round(1)

       preco_custo  valor_unitario  quantidade  valor_final  lucro
count         16.0            16.0        16.0         16.0   16.0
mean          43.0            83.4         1.0         83.4   40.4
std           10.5            19.1         0.0         19.1    8.6
min           27.9            55.9         1.0         55.9   28.0
25%           27.9            55.9         1.0         55.9   28.0
50%           49.9            95.9         1.0         95.9   46.0
75%           49.9            95.9         1.0         95.9   46.0
max           49.9            95.9         1.0         95.9   46.0

### Testes lógicos com loc

In [55]:
df.head()

,matricula_funcionario,nome_funcionario,cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,categoria,preco_custo,valor_unitario,quantidade,dt_entrega,valor_final,lucro
dt_venda,,,,,,,,,,,,,,
2020-08-25 10:04:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10013,Fogão,Eletrodomésticos,210.9,404.1,3,2020-08-31 16:39:00,1212.3,1001.4
2020-06-10 15:34:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10011,Liquidificador,Cozinha,59.9,142.4,2,2020-06-11 13:59:00,284.8,224.9
2019-03-21 15:58:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10013,Fogão,Eletrodomésticos,210.9,404.1,2,2019-03-28 09:44:00,808.2,597.3
2019-09-16 14:46:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10004,Máquina Lavar Roupa,Eletrodomésticos,1099.0,1709.1,2,2019-09-20 09:22:00,3418.2,2319.2
2019-11-25 16:28:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10005,Notebook,Eletrônicos,2299.9,3199.0,2,2019-11-26 13:42:00,6398.0,4098.1

In [66]:
df.loc[df['codigo_produto'] == '10017', 'preco_custo':]

,preco_custo,valor_unitario,quantidade,dt_entrega,valor_final,lucro
dt_venda,,,,,,
2019-02-01 13:21:00,1189.9,1899.5,3,2019-02-04 17:02:00,5698.5,4508.6
2019-02-17 14:03:00,1189.9,1899.5,3,2019-02-19 10:29:00,5698.5,4508.6
2019-06-27 10:57:00,1189.9,1899.5,1,2019-07-01 15:20:00,1899.5,709.6
2020-08-26 12:36:00,1189.9,1899.5,1,2020-08-29 10:43:00,1899.5,709.6
2019-05-27 14:41:00,1189.9,1899.5,4,2019-05-30 09:26:00,7598.0,6408.1
...,...,...,...,...,...,...
2019-01-20 10:45:00,1189.9,1899.5,4,2019-01-22 12:52:00,7598.0,6408.1
2019-07-31 09:59:00,1189.9,1899.5,4,2019-08-02 11:03:00,7598.0,6408.1
2020-06-28 09:25:00,1189.9,1899.5,4,2020-07-03 11:44:00,7598.0,6408.1
2020-11-02 09:04:00,1189.9,1899.5,2,2020-11-04 12:12:00,3799.0,2609.1
2019-04-17 15:36:00,1189.9,1899.5,4,2019-04-24 15:55:00,7598.0,6408.1

### Aplicando queries

```python
query()
```

In [67]:
df.head()

,matricula_funcionario,nome_funcionario,cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,categoria,preco_custo,valor_unitario,quantidade,dt_entrega,valor_final,lucro
dt_venda,,,,,,,,,,,,,,
2020-08-25 10:04:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10013,Fogão,Eletrodomésticos,210.9,404.1,3,2020-08-31 16:39:00,1212.3,1001.4
2020-06-10 15:34:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10011,Liquidificador,Cozinha,59.9,142.4,2,2020-06-11 13:59:00,284.8,224.9
2019-03-21 15:58:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10013,Fogão,Eletrodomésticos,210.9,404.1,2,2019-03-28 09:44:00,808.2,597.3
2019-09-16 14:46:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10004,Máquina Lavar Roupa,Eletrodomésticos,1099.0,1709.1,2,2019-09-20 09:22:00,3418.2,2319.2
2019-11-25 16:28:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10005,Notebook,Eletrônicos,2299.9,3199.0,2,2019-11-26 13:42:00,6398.0,4098.1

In [68]:
df.query("categoria == 'Cozinha'")

,matricula_funcionario,nome_funcionario,cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,categoria,preco_custo,valor_unitario,quantidade,dt_entrega,valor_final,lucro
dt_venda,,,,,,,,,,,,,,
2020-06-10 15:34:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10011,Liquidificador,Cozinha,59.9,142.4,2,2020-06-11 13:59:00,284.8,224.9
2019-11-01 11:05:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10010,Fritadeira elétrica,Cozinha,187.9,340.0,2,2019-11-01 13:45:00,680.0,492.1
2020-04-01 16:50:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10010,Fritadeira elétrica,Cozinha,187.9,340.0,2,2020-04-02 15:20:00,680.0,492.1
2020-01-27 17:32:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10010,Fritadeira elétrica,Cozinha,187.9,340.0,2,2020-01-28 16:20:00,680.0,492.1
2020-07-02 12:27:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10012,Processador de alimentos,Cozinha,110.0,189.9,2,2020-07-02 16:27:00,379.8,269.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-03-23 10:05:00,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10011,Liquidificador,Cozinha,59.9,142.4,2,2019-03-23 14:35:00,284.8,224.9
2020-08-20 11:41:00,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10012,Processador de alimentos,Cozinha,110.0,189.9,4,2020-08-20 15:24:00,759.6,649.6
2020-02-20 14:27:00,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10007,Batedeira,Cozinha,49.9,95.9,2,2020-02-21 13:22:00,191.8,141.9
2020-05-26 16:07:00,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10007,Batedeira,Cozinha,49.9,95.9,4,2020-05-27 09:32:00,383.6,333.7
2020-10-22 17:06:00,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10012,Processador de alimentos,Cozinha,110.0,189.9,2,2020-10-23 11:05:00,379.8,269.8

In [69]:
df.query("nome_loja == 'Filial SP' and descricao_produto == 'Fritadeira elétrica'") # PODEMOS USAR .describe()

,matricula_funcionario,nome_funcionario,cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,categoria,preco_custo,valor_unitario,quantidade,dt_entrega,valor_final,lucro
dt_venda,,,,,,,,,,,,,,
2019-11-01 11:05:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10010,Fritadeira elétrica,Cozinha,187.9,340.0,2,2019-11-01 13:45:00,680.0,492.1
2020-04-01 16:50:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10010,Fritadeira elétrica,Cozinha,187.9,340.0,2,2020-04-02 15:20:00,680.0,492.1
2020-01-27 17:32:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10010,Fritadeira elétrica,Cozinha,187.9,340.0,2,2020-01-28 16:20:00,680.0,492.1
2019-11-15 10:45:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10010,Fritadeira elétrica,Cozinha,187.9,340.0,2,2019-11-15 11:17:00,680.0,492.1
2019-03-29 10:37:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10010,Fritadeira elétrica,Cozinha,187.9,340.0,2,2019-03-29 11:06:00,680.0,492.1
2020-02-05 13:13:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10010,Fritadeira elétrica,Cozinha,187.9,340.0,3,2020-02-06 09:03:00,1020.0,832.1
2019-05-21 15:24:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10010,Fritadeira elétrica,Cozinha,187.9,340.0,3,2019-05-22 13:50:00,1020.0,832.1
2019-09-21 15:58:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10010,Fritadeira elétrica,Cozinha,187.9,340.0,3,2019-09-22 13:34:00,1020.0,832.1
2019-01-03 17:09:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10010,Fritadeira elétrica,Cozinha,187.9,340.0,3,2019-01-04 14:53:00,1020.0,832.1
2020-02-16 14:35:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10010,Fritadeira elétrica,Cozinha,187.9,340.0,1,2020-02-16 14:37:00,340.0,152.1
2020-12-06 12:33:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10010,Fritadeira elétrica,Cozinha,187.9,340.0,4,2020-12-06 14:40:00,1360.0,1172.1
2019-10-24 10:30:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10010,Fritadeira elétrica,Cozinha,187.9,340.0,4,2019-10-24 14:49:00,1360.0,1172.1
2019-12-31 17:22:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10010,Fritadeira elétrica,Cozinha,187.9,340.0,1,2020-01-01 17:07:00,340.0,152.1
2019-07-11 13:37:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10010,Fritadeira elétrica,Cozinha,187.9,340.0,4,2019-07-11 14:06:00,1360.0,1172.1
2020-12-11 09:23:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10010,Fritadeira elétrica,Cozinha,187.9,340.0,4,2020-12-11 10:33:00,1360.0,1172.1
2020-04-24 12:06:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10010,Fritadeira elétrica,Cozinha,187.9,340.0,1,2020-04-25 11:16:00,340.0,152.1
2019-05-05 11:05:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10010,Fritadeira elétrica,Cozinha,187.9,340.0,4,2019-05-05 12:23:00,1360.0,1172.1
2019-08-03 11:33:00,123456777,Marcos Coelho,Vendedor,CL003,Filial SP,10010,Fritadeira elétrica,Cozinha,187.9,340.0,4,2019-08-03 15:22:00,1360.0,1172.1
2020-10-31 17:05:00,123456777,Marcos Coelho,Vendedor,CL003,Filial SP,10010,Fritadeira elétrica,Cozinha,187.9,340.0,4,2020-11-01 10:21:00,1360.0,1172.1
2020-08-30 15:08:00,123456777,Marcos Coelho,Vendedor,CL003,Filial SP,10010,Fritadeira elétrica,Cozinha,187.9,340.0,4,2020-08-30 16:39:00,1360.0,1172.1
2020-08-08 15:46:00,123456777,Marcos Coelho,Vendedor,CL003,Filial SP,10010,Fritadeira elétrica,Cozinha,187.9,340.0,2,2020-08-09 14:48:00,680.0,492.1
2019-03-25 11:46:00,123456777,Marcos Coelho,Vendedor,CL003,Filial SP,10010,Fritadeira elétrica,Cozinha,187.9,340.0,2,2019-03-26 09:02:00,680.0,492.1
2019-07-13 12:23:00,123456777,Marcos Coelho,Vendedor,CL003,Filial SP,10010,Fritadeira elétrica,Cozinha,187.9,340.0,4,2019-07-13 15:55:00,1360.0,1172.1
2019-09-14 10:59:00,123456777,Marcos Coelho,Vendedor,CL003,Filial SP,10010,Fritadeira elétrica,Cozinha,187.9,340.0,1,2019-09-14 13:41:00,340.0,152.1
2020-12-25 15:55:00,123456777,Marcos Coelho,Vendedor,CL003,Filial SP,10010,Fritadeira elétrica,Cozinha,187.9,340.0,1,2020-12-25 16:43:00,340.0,152.1
2019-09-24 17:57:00,123456777,Marcos Coelho,Vendedor,CL003,Filial SP,10010,Fritadeira elétrica,Cozinha,187.9,340.0,1,2019-09-25 09:23:00,340.0,152.1
2019-10-29 09:48:00,123456777,Marcos Coelho,Vendedor,CL003,Filial SP,10010,Fritadeira elétrica,Cozinha,187.9,340.0,3,2019-10-29 12:34:00,1020.0,832.1
2019-02-22 10:55:00,123456777,Marcos Coelho,Vendedor,CL003,Filial SP,10010,Fritadeira elétrica,Cozinha,187.9,340.0,3,2019-02-22 14:34:00,1020.0,832.1
2019-02-25 10:37:00,123456777,Marcos Coelho,Vendedor,CL003,Filial SP,10010,Fritadeira elétrica,Cozinha,187.9,340.0,4,2019-02-25 11:34:00,1360.0,1172.1
2019-09-27 09:14:00,123456888,Rita Sampaio,Vendedor,CL003,Filial SP,10010,Fritadeira elétrica,Cozinha,187.9,340.0,1,2019-09-27 11:07:00,340.0,152.1
2019-10-02 17:09:00,123456888,Rita Sampaio,Vendedor,CL003,Filial SP,10010,Fritadeira elétrica,Cozinha,187.9,340.0,2,2019-10-03 09:32:00,680.0,492.1
2020-03-22 11:29:00,123456888,Rita Sampaio,Vendedor,CL003,Filial SP,10010,Fritadeira elétrica,Cozinha,187.9,340.0,2,2020-03-23 11:26:00,680.0,492.1
2020-08-29 14:32:00,123456888,Rita Sampaio,Vendedor,CL003,Filial SP,10010,Fritadeira elétrica,Cozinha,187.9,340.0,3,2020-08-30 10:23:00,1020.0,832.1
2019-09-01 09:53:00,123456888,Rita Sampaio,Vendedor,CL003,Filial SP,10010,Fritadeira elétrica,Cozinha,187.9,340.0,3,2019-09-01 10:55:00,1020.0,832.1
2020-09-27 17:25:00,123456888,Rita Sampaio,Vendedor,CL003,Filial SP,10010,Fritadeira elétrica,Cozinha,187.9,340.0,3,2020-09-28 10:38:00,1020.0,832.1
2020-05-17 09:47:00,123456888,Rita Sampaio,Vendedor,CL003,Filial SP,10010,Fritadeira elétrica,Cozinha,187.9,340.0,4,2020-05-17 13:02:00,1360.0,1172.1
2020-07-17 12:06:00,123456888,Rita Sampaio,Vendedor,CL003,Filial SP,10010,Fritadeira elétrica,Cozinha,187.9,340.0,1,2020-07-18 09:33:00,340.0,152.1
2019-09-17 17:10:00,123456888,Rita Sampaio,Vendedor,CL003,Filial SP,10010,Fritadeira elétrica,Cozinha,187.9,340.0,4,2019-09-18 16:12:00,1360.0,1172.1
2019-08-21 16:21:00,123456888,Rita Sampaio,Vendedor,CL003,Filial SP,10010,Fritadeira elétrica,Cozinha,187.9,340.0,1,2019-08-22 10:14:00,340.0,152.1
2019-09-10 15:23:00,123456888,Rita Sampaio,Vendedor,CL003,Filial SP,10010,Fritadeira elétrica,Cozinha,187.9,340.0,2,2019-09-10 15:34:00,680.0,492.1
2019-09-13 17:19:00,123456888,Rita Sampaio,Vendedor,CL003,Filial SP,10010,Fritadeira elétrica,Cozinha,187.9,340.0,3,2019-09-14 16:32:00,1020.0,832.1

In [70]:
df_filial_sp_ou_fritadeira =  df.query("nome_loja == 'Filial SP' or descricao_produto == 'Fritadeira elétrica'")

In [71]:
df_filial_sp_ou_fritadeira.head()

,matricula_funcionario,nome_funcionario,cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,categoria,preco_custo,valor_unitario,quantidade,dt_entrega,valor_final,lucro
dt_venda,,,,,,,,,,,,,,
2020-08-25 10:04:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10013,Fogão,Eletrodomésticos,210.9,404.1,3,2020-08-31 16:39:00,1212.3,1001.4
2020-06-10 15:34:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10011,Liquidificador,Cozinha,59.9,142.4,2,2020-06-11 13:59:00,284.8,224.9
2019-03-21 15:58:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10013,Fogão,Eletrodomésticos,210.9,404.1,2,2019-03-28 09:44:00,808.2,597.3
2019-09-16 14:46:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10004,Máquina Lavar Roupa,Eletrodomésticos,1099.0,1709.1,2,2019-09-20 09:22:00,3418.2,2319.2
2019-11-25 16:28:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10005,Notebook,Eletrônicos,2299.9,3199.0,2,2019-11-26 13:42:00,6398.0,4098.1

## Agrupando dados

### a função groupby

```python
groupby()
```

In [72]:
df.head()

,matricula_funcionario,nome_funcionario,cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,categoria,preco_custo,valor_unitario,quantidade,dt_entrega,valor_final,lucro
dt_venda,,,,,,,,,,,,,,
2020-08-25 10:04:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10013,Fogão,Eletrodomésticos,210.9,404.1,3,2020-08-31 16:39:00,1212.3,1001.4
2020-06-10 15:34:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10011,Liquidificador,Cozinha,59.9,142.4,2,2020-06-11 13:59:00,284.8,224.9
2019-03-21 15:58:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10013,Fogão,Eletrodomésticos,210.9,404.1,2,2019-03-28 09:44:00,808.2,597.3
2019-09-16 14:46:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10004,Máquina Lavar Roupa,Eletrodomésticos,1099.0,1709.1,2,2019-09-20 09:22:00,3418.2,2319.2
2019-11-25 16:28:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10005,Notebook,Eletrônicos,2299.9,3199.0,2,2019-11-26 13:42:00,6398.0,4098.1

In [80]:
df_agrupado_nome_loja = df.groupby('nome_loja')

In [83]:
df_agrupado_nome_loja.median()

C:\Users\Win10\AppData\Local\Temp\ipykernel_16880\1041661229.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.median is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_agrupado_nome_loja.median()

             preco_custo  valor_unitario  quantidade  valor_final  lucro
nome_loja
Filial ES          329.9           674.1         3.0       1348.2  832.1
Filial MG          210.9           404.1         2.0       1212.3  670.7
Filial SP          210.9           404.1         2.0       1212.3  709.6
Loja Matriz        329.9           674.1         2.0       1348.2  694.8

In [94]:
df.groupby('nome_loja')['lucro'].sum().round(2)

nome_loja
Filial ES      1307064.20
Filial MG      1185249.53
Filial SP      1224188.71
Loja Matriz    1351807.27
Name: lucro, dtype: float64

### Funções de agregação

In [102]:
df.groupby('descricao_produto').agg({
    'valor_final': np.sum,
    'valor_unitario': np.mean,
    'lucro': np.sum
})

# PARA O VALOR FINAL: ELE SOMA TUDO
# PARA O VALOR UNITÁRIO: ELE CALCULA A MÉDIA
# PARA O LUCRO: ELE SOMA TUDO

                          valor_final  valor_unitario      lucro
descricao_produto
Aspirador de pó              83935.80          189.90   68556.10
Batedeira                    33085.50           95.90   26299.10
Cafeteira                    90883.10          284.90   69136.70
Cama Box                    685719.50         1899.50  511994.10
Colchão                      92463.00          249.90   75978.00
Ferro de passar              22248.20           55.90   18035.30
Fogão                       160831.80          404.10  126455.10
Fritadeira elétrica         137700.00          340.00  108951.30
Geladeira                   456599.10         1346.90  357213.30
Guarda Roupa                355644.00          999.00  282648.90
Impressora                  254809.80          674.10  204005.20
Liquidificador               55108.80          142.40   45764.40
Microondas                  142155.00          364.50  111537.00
Máquina Lavar Roupa         632367.00         1709.10  457626.00
Notebook                   1001287.00         3199.00  700000.10
Processador de alimentos     67984.20          189.90   52254.20
Smartphone                  627160.60         1676.90  488576.00
Sofá                        444882.00         1399.00  335875.80
Tablet                      541465.80         1424.91  417620.80
Televisão                   818516.41         2279.99  609782.31

### Agrupando dados pelo índice

In [106]:
df.groupby(df.index.year).agg({
    'valor_final': np.sum,
    'lucro': np.sum
})

          valor_final       lucro
dt_venda
2019       3505589.26  2649107.66
2020       3199257.35  2419202.05

### Agrupando dados por mais de uma coluna

In [107]:
df.head()

,matricula_funcionario,nome_funcionario,cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,categoria,preco_custo,valor_unitario,quantidade,dt_entrega,valor_final,lucro
dt_venda,,,,,,,,,,,,,,
2020-08-25 10:04:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10013,Fogão,Eletrodomésticos,210.9,404.1,3,2020-08-31 16:39:00,1212.3,1001.4
2020-06-10 15:34:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10011,Liquidificador,Cozinha,59.9,142.4,2,2020-06-11 13:59:00,284.8,224.9
2019-03-21 15:58:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10013,Fogão,Eletrodomésticos,210.9,404.1,2,2019-03-28 09:44:00,808.2,597.3
2019-09-16 14:46:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10004,Máquina Lavar Roupa,Eletrodomésticos,1099.0,1709.1,2,2019-09-20 09:22:00,3418.2,2319.2
2019-11-25 16:28:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10005,Notebook,Eletrônicos,2299.9,3199.0,2,2019-11-26 13:42:00,6398.0,4098.1

In [110]:
df.groupby(['nome_loja', 'nome_funcionario']).agg({
    'preco_custo': np.sum,
    'lucro': np.sum
})

                              preco_custo      lucro
nome_loja   nome_funcionario
Filial ES   Mário Henrique       124140.6  419573.32
            Pamela Lima          145756.4  453096.95
            Victor Hugo          135572.9  434393.93
Filial MG   Marta Cury           128895.0  425381.88
            Reginaldo Sodré      129144.9  370046.28
            Ricardo Lemos        126267.4  389821.37
Filial SP   Felipe Marinho       137759.0  462702.50
            Marcos Coelho        127575.6  352127.94
            Rita Sampaio         129223.6  409358.27
Loja Matriz Jorge Mateus         137759.5  399043.91
            José Maria           164455.5  489595.31
            Maria das Graças     149986.5  463168.05

In [44]:
df.head()

,matricula_funcionario,nome_funcionario,cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,categoria,preco_custo,valor_unitario,quantidade,dt_entrega,valor_final
dt_venda,,,,,,,,,,,,,
2020-08-25 10:04:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10013,Fogão,Eletrodomésticos,210.9,404.1,3,2020-08-31 16:39:00,1212.3
2020-06-10 15:34:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10011,Liquidificador,Cozinha,59.9,142.4,2,2020-06-11 13:59:00,284.8
2019-03-21 15:58:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10013,Fogão,Eletrodomésticos,210.9,404.1,2,2019-03-28 09:44:00,808.2
2019-09-16 14:46:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10004,Máquina Lavar Roupa,Eletrodomésticos,1099.0,1709.1,2,2019-09-20 09:22:00,3418.2
2019-11-25 16:28:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10005,Notebook,Eletrônicos,2299.9,3199.0,2,2019-11-26 13:42:00,6398.0

In [111]:
df.groupby(['categoria', 'descricao_produto']).agg({
    'valor_unitario': np.sum,
    'lucro': np.sum    
})

                                           valor_unitario      lucro
categoria        descricao_produto
Casa             Aspirador de pó                 32852.70   68556.10
                 Cama Box                       277327.00  511994.10
                 Colchão                         37485.00   75978.00
                 Ferro de passar                  8440.90   18035.30
                 Guarda Roupa                   148851.00  282648.90
                 Sofá                           193062.00  335875.80
Cozinha          Batedeira                       13042.40   26299.10
                 Cafeteira                       38746.40   69136.70
                 Fritadeira elétrica             52020.00  108951.30
                 Liquidificador                  22214.40   45764.40
                 Processador de alimentos        27155.70   52254.20
Eletrodomésticos Fogão                           65868.30  126455.10
                 Geladeira                      191259.80  357213.30
                 Microondas                      59049.00  111537.00
                 Máquina Lavar Roupa            271746.90  457626.00
                 Televisão                      339718.51  609782.31
Eletrônicos      Impressora                     103811.40  204005.20
                 Notebook                       419069.00  700000.10
                 Smartphone                     258242.60  488576.00
                 Tablet                         220861.05  417620.80

### Agrupando dados por tabelas dinâmicas (Pivot Tables)

```python
pivot_table()
```

In [112]:
df.pivot_table(index='nome_funcionario', aggfunc=np.sum)

C:\Users\Win10\AppData\Local\Temp\ipykernel_16880\3187175805.py:1: FutureWarning: pivot_table dropped a column because it failed to aggregate. This behavior is deprecated and will raise in a future version of pandas. Select only the columns that can be aggregated.
  df.pivot_table(index='nome_funcionario', aggfunc=np.sum)

,lucro,preco_custo,quantidade,valor_final,valor_unitario
nome_funcionario,,,,,
Felipe Marinho,462702.50,137759.0,655,600461.50,236958.50
Jorge Mateus,399043.91,137759.5,597,536803.41,230777.71
José Maria,489595.31,164455.5,681,654050.81,277841.78
Marcos Coelho,352127.94,127575.6,555,479703.54,220283.55
Maria das Graças,463168.05,149986.5,667,613154.55,251915.25
Marta Cury,425381.88,128895.0,613,554276.88,221689.53
Mário Henrique,419573.32,124140.6,553,543713.92,208046.00
Pamela Lima,453096.95,145756.4,599,598853.35,242313.75
Reginaldo Sodré,370046.28,129144.9,608,499191.18,219619.97
Ricardo Lemos,389821.37,126267.4,603,516088.77,217957.76
Rita Sampaio,409358.27,129223.6,589,538581.87,220326.10
Victor Hugo,434393.93,135572.9,640,569966.83,233094.16

## Iterando sobre um DataFrame

### iteritems()

- retorna uma tupla
- nome_coluna, conteúdo

In [113]:
df.head()

,matricula_funcionario,nome_funcionario,cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,categoria,preco_custo,valor_unitario,quantidade,dt_entrega,valor_final,lucro
dt_venda,,,,,,,,,,,,,,
2020-08-25 10:04:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10013,Fogão,Eletrodomésticos,210.9,404.1,3,2020-08-31 16:39:00,1212.3,1001.4
2020-06-10 15:34:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10011,Liquidificador,Cozinha,59.9,142.4,2,2020-06-11 13:59:00,284.8,224.9
2019-03-21 15:58:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10013,Fogão,Eletrodomésticos,210.9,404.1,2,2019-03-28 09:44:00,808.2,597.3
2019-09-16 14:46:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10004,Máquina Lavar Roupa,Eletrodomésticos,1099.0,1709.1,2,2019-09-20 09:22:00,3418.2,2319.2
2019-11-25 16:28:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10005,Notebook,Eletrônicos,2299.9,3199.0,2,2019-11-26 13:42:00,6398.0,4098.1

In [115]:
for col_name, col_content in df.iteritems():
    print(col_content)
    break

dt_venda
2020-08-25 10:04:00    123456999
2020-06-10 15:34:00    123456999
2019-03-21 15:58:00    123456999
2019-09-16 14:46:00    123456999
2019-11-25 16:28:00    123456999
                         ...
2019-04-17 15:36:00    123457113
2020-01-21 15:46:00    123457113
2020-10-22 17:06:00    123457113
2019-02-18 16:04:00    123457113
2019-03-18 15:40:00    123457113
Name: matricula_funcionario, Length: 3000, dtype: object

C:\Users\Win10\AppData\Local\Temp\ipykernel_16880\222387695.py:1: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for col_name, col_content in df.iteritems():

### iterrows()

- retorna uma tupla
- nome da linha, conteúdo da linha

In [116]:
df.head()

,matricula_funcionario,nome_funcionario,cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,categoria,preco_custo,valor_unitario,quantidade,dt_entrega,valor_final,lucro
dt_venda,,,,,,,,,,,,,,
2020-08-25 10:04:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10013,Fogão,Eletrodomésticos,210.9,404.1,3,2020-08-31 16:39:00,1212.3,1001.4
2020-06-10 15:34:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10011,Liquidificador,Cozinha,59.9,142.4,2,2020-06-11 13:59:00,284.8,224.9
2019-03-21 15:58:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10013,Fogão,Eletrodomésticos,210.9,404.1,2,2019-03-28 09:44:00,808.2,597.3
2019-09-16 14:46:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10004,Máquina Lavar Roupa,Eletrodomésticos,1099.0,1709.1,2,2019-09-20 09:22:00,3418.2,2319.2
2019-11-25 16:28:00,123456999,Felipe Marinho,Vendedor,CL003,Filial SP,10005,Notebook,Eletrônicos,2299.9,3199.0,2,2019-11-26 13:42:00,6398.0,4098.1

In [120]:
for row_name, row_content in df.iterrows():
    print(row_name, row_content)
    break

2020-08-25 10:04:00 matricula_funcionario              123456999
nome_funcionario              Felipe Marinho
cargo                               Vendedor
codigo_loja                            CL003
nome_loja                          Filial SP
codigo_produto                         10013
descricao_produto                      Fogão
categoria                   Eletrodomésticos
preco_custo                            210.9
valor_unitario                         404.1
quantidade                                 3
dt_entrega               2020-08-31 16:39:00
valor_final                           1212.3
lucro                                 1001.4
Name: 2020-08-25 10:04:00, dtype: object